import assert from 'node:assert/strict';
import {inflateRawSync} from 'node:zlib';
import {waitStep,clickText,clickSelector,next,nav,ab,state,sleep,evaluate} from './tour-browser-driver.mjs';
const port=process.env.QA_PORT||'3205';
const recapIds=[];
async function recap(id,label){await waitStep(id);const tools=JSON.parse(evaluate('Array.from(document.querySelectorAll("[data-tour-step] dl dd")).map(e=>e.textContent)'));assert(tools.length>3);assert(tools.every(t=>t.trim().length>10));recapIds.push(id);await clickText(label);}
async function draftEmail(){ab('click','[data-tour="inbox-email-reply"]');await sleep(500);await clickText('Draft a response','[role="menuitem"]');}
ab('open',`http://localhost:${port}/app?tour=welcome`);await sleep(800);
evaluate('Array.from(document.querySelectorAll("button")).find(e=>e.textContent.includes("Full Guided Tour")).click()');
await waitStep('you-answer');await clickText('Simulate call');await clickText('Simulate call');
await waitStep('save-first-lead');await sleep(5200);await clickText('Save lead');
await next('lead-detail-overview','go-tasks-confirmation');
await nav('go-tasks-confirmation','/app/tasks','open-confirmation-task');
await clickSelector('[data-tour="task-confirmation-link"]');await waitStep('approve-1');await clickText('Approve & send (simulated)');
await nav('go-leads-after-confirm','/app/leads','open-jordan-after-confirm');
await clickSelector('button[aria-label="Exit tour"]');await clickText('Start Tour');await waitStep('open-jordan-after-confirm');assert.equal(state().url,'/app/leads');
await clickSelector('[data-tour="leads-first-row"] a');await next('timeline-after-confirm','rep-assisted-call-recap');
await recap('rep-assisted-call-recap','Continue to the website-lead callback');
await waitStep('speed-to-lead');await clickText('Open form');
for(const [name,value] of [['First name','Taylor'],['Last name','Morgan'],['Phone','4145550198'],['Email (optional)','taylor.morgan@example.com'],['Street address (optional)','212 Oak Street'],['City (optional)','Pewaukee'],['ZIP code (optional)','53072']])ab('find','label',name,'fill',value);
await clickText('Submit Request');await waitStep('answer-call');await clickText('Simulate call');await clickText('Simulate call');
await nav('follow-form-notifications','/app/tasks','open-form-confirmation-task');
await clickSelector('[data-tour="task-confirmation-link"]');await waitStep('approve-form-confirmation');assert(state().text.includes('Taylor'));
await clickText('Approve & send (simulated)');await recap('speed-to-lead-recap',"Continue to the customer's urgent text");
await waitStep('text');ab('reload');await waitStep('text');await sleep(500);await clickText('Send text');
await waitStep('check-jess-availability');assert(state().text.includes('Taylor Morgan'));await clickSelector('[data-tour="inbox-ai-insight-check"]');
await waitStep('jess-calendar');assert(state().url.includes('slot='));await next('jess-calendar','back-to-inbox-reschedule');
await clickText('Return to the customer’s text');await waitStep('draft-reschedule-offer');await clickSelector('[data-tour="inbox-ai-insight-draft"]');
await waitStep('approve-reschedule-offer');assert(evaluate('document.querySelector("textarea").value').includes('Hi Taylor'));
await clickText('Approve & send (simulated)');await waitStep('go-appointments-after-reschedule');assert(evaluate('document.body.innerText').includes('Hi Taylor, your updated inspection'));
await nav('go-appointments-after-reschedule','/app/appointments','jess-booked-after-reschedule');assert(evaluate('document.body.innerText').includes('Taylor Morgan'));
await next('jess-booked-after-reschedule','urgent-reschedule-recap');await recap('urgent-reschedule-recap','Continue to the inbound email workflow');
await waitStep('email');await clickText('Receive email lead');await waitStep('reply-email');
await draftEmail();await waitStep('send-email-reply');assert(evaluate('document.querySelector("textarea").value').includes('3 PM'));
ab('reload');await waitStep('reply-email');await sleep(600);await draftEmail();await waitStep('send-email-reply');
await clickText('Send reply (simulated)');await recap('inbound-email-recap','Continue to pipeline and quoting');
await nav('pipeline','/app/pipeline','pipeline-view');await sleep(3100);await next('pipeline-view','quote-tool');
await nav('quote-tool','/app/quote-tool','quote-tool-view');ab('click','[data-tour="quote-lead-select"]');await sleep(400);await clickText('Greg Tomlinson — windows','[role="option"]');
await waitStep('quote-property-profile');await clickText('Generate demo property profile');await waitStep('quote-generate-ballpark');
ab('fill','#quote-window-count','12');await clickText('Generate internal ballpark');await waitStep('quote-review-result');
const quoteBefore=evaluate('document.querySelector("[data-tour=quote-result]").innerText');assert(quoteBefore.includes('12 windows'));
ab('reload');await waitStep('quote-review-result');assert(evaluate('document.querySelector("[data-tour=quote-result]").innerText').includes('12 windows'));
await next('quote-review-result','quote-recap');await recap('quote-recap','Continue to reputation management');
await nav('feedback','/app/feedback','feedback-view');await clickSelector('[data-tour="feedback-new-review"]');await waitStep('feedback-analyze');
await clickText('Have AI analyze it');await waitStep('feedback-publish');await clickText('Approve & post to Google (simulated)');await recap('feedback-recap','Continue to workflow orchestration');
await nav('automations','/app/automations','automations-view');ab('click','[data-tour="automation-modules-tab"]');await waitStep('automation-run-analysis');
await clickSelector('[data-tour="automation-run-lead_intake_analysis"]');await recap('automation-recap','Inspect the structured output first');
await waitStep('automation-output-review');assert(state().text.includes('Last test output'));await clickText('Continue to management reporting');
await nav('reports','/app/reports','reports-view');await sleep(3100);await next('reports-view','settings');
await nav('settings','/app/settings','settings-view');await sleep(3100);await next('settings-view','management-recap');
await recap('management-recap','Finish the full tour');if(process.env.QA_SCREENSHOT) ab('screenshot',process.env.QA_SCREENSHOT);await clickText('Finish & explore the CRM');
const cookies=JSON.parse(ab('cookies','--json')).data.cookies;
const chunks=cookies.filter(c=>/^northstar_demo_state_\d+$/.test(c.name)).sort((a,b)=>Number(a.name.split('_').at(-1))-Number(b.name.split('_').at(-1)));
const db=JSON.parse(inflateRawSync(Buffer.from(chunks.map(c=>c.value).join(''),'base64url')).toString());
const taylor=db.leads.find(l=>l.first_name==='Taylor');const greg=db.leads.find(l=>l.first_name==='Greg');
assert.equal(db.leads.length,3);assert.equal(taylor.service_type,'storm_damage');assert.equal(greg.stage,'contacted');
assert.equal(db.appointments.find(a=>a.lead_id===taylor.id).status,'rescheduled');assert.equal(db.appointments.filter(a=>a.lead_id===greg.id).length,0);
assert.equal(db.quotes.length,1);assert.equal(db.quotes[0].lead_id,greg.id);assert(db.quotes[0].line_items.some(l=>l.detail.includes('12 windows')));
assert.equal(db.automationRuns.length,1);assert.equal(db.feedback.length,1);assert.equal(recapIds.length,8);
const gregEmail=db.communications.find(c=>c.metadata.demo_action==='executive_inbound_window_email');assert.equal(gregEmail.metadata.suggested_slots.length,3);
const slots=gregEmail.metadata.suggested_slots.map(s=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'short',hour:'numeric',hourCycle:'h23'}).format(new Date(s.start)));
assert(slots.every(s=>!s.includes('Sat')&&!s.includes('Sun')));
assert(gregEmail.metadata.suggested_slots.every(s=>Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'numeric',hourCycle:'h23'}).format(new Date(s.start)))>=15));
console.log('PASS',JSON.stringify({recaps:recapIds,leads:db.leads.length,appointments:db.appointments.length,quotes:db.quotes.length,feedback:db.feedback.length,runs:db.automationRuns.length,cookieBytes:cookies.reduce((n,c)=>n+c.name.length+c.value.length+2,0),emailSlots:slots}));
const errors=ab('errors').trim(); assert.equal(errors,'',errors); console.log('BROWSER ERRORS: none');
