/** Display names describe responsibilities, not a claim that these are MCP servers. */
export const TOOL_EXPLANATIONS: Record<string, string> = {
  "call.summarize": "Condenses the conversation into a CRM note and structured follow-up details.",
  "lead.update": "Updates the selected lead’s internal qualification signals.",
  "phone.session": "Starts the browser call and tracks its lifecycle.",
  "transcript.capture": "Collects the conversation so the team can inspect what was said.",
  "lead.extract": "Turns the conversation into contact and project fields for the rep to review.",
  "availability.search": "Checks bookable openings against the demo calendar and existing appointments.",
  "lead.create": "Saves the reviewed intake as a CRM lead.",
  "appointment.create": "Books the agreed opening and links it to the customer.",
  "message.draft": "Prepares the confirmation without sending it.",
  "message.approve": "Records human approval and logs the simulated send.",
  "audit.append": "Adds a traceable record of the action and its outcome.",
  "form.ingest": "Validates and accepts the homeowner’s website request.",
  "contact.match": "Resolves the customer using explicit identity or normalized contact details.",
  "voice.call": "Runs the AI callback, or the silent simulation, to gather missing details.",
  "lead.qualify": "Classifies service needs, urgency and next actions from the gathered context.",
  "task.create": "Creates the follow-up work and links it to the lead.",
  "sms.ingest": "Logs the customer’s incoming text in the conversation.",
  "lead.context": "Reads the customer’s existing request and appointment before proposing a change.",
  "intent.classify": "Recognizes the urgent request for an earlier inspection.",
  "reply.draft": "Writes an editable offer using the verified appointment opening.",
  "appointment.reschedule": "Moves the appointment after the simulated customer accepts the offer.",
  "reminder.update": "Updates the confirmation and reminder schedule for the new appointment.",
  "email.ingest": "Stores the incoming email and its sender as a CRM conversation.",
  "lead.upsert": "Creates or updates the matching lead without treating every touchpoint as a new person.",
  "intent.extract": "Pulls the project scope and timing request out of the email.",
  "reply.generate": "Prepares an editable email response using the available customer context.",
  "communication.append": "Logs the reviewed reply in the customer’s communication history.",
  "lead.read": "Loads the selected CRM record as input to the workflow.",
  "property.lookup": "Builds a clearly labeled simulated property profile for estimator preparation.",
  "pricing.calculate": "Calculates the range with fixed pricing rules and job inputs.",
  "estimate.explain": "Summarizes the calculator output; local demo narration uses a template.",
  "inspection_questions.generate": "Lists missing facts that an inspection must resolve before final pricing.",
  "quote.save": "Saves the internal range and its assumptions against the lead.",
  "activity.append": "Adds the workflow outcome to the lead’s timeline.",
  "review.ingest": "Loads the sample review as the input to reputation analysis.",
  "feedback.analyze": "Structures the review into sentiment, complaint themes and a suggested response.",
  "risk.classify": "Identifies escalation risk and the recommended recovery action.",
  "response.draft": "Prepares an editable public response for a manager’s review.",
  "review.publish": "Records the approved response as a simulated public post.",
  "lead.analyze": "Applies demo qualification rules to produce structured signals and next-action recommendations.",
  "crm_note.append": "Writes the permitted internal summary to CRM history.",
  "task.suggest": "Returns the recommended follow-up work for the team.",
  "automation_run.append": "Saves the module’s status, actions and structured output in the run history.",
  "pipeline.aggregate": "Computes channel, stage and value metrics from the CRM records created in the demo.",
  "insights.compute": "Applies reporting rules to surface urgency, stalled work and channel patterns.",
  "settings.read": "Shows the manager-owned AI and communication configuration.",
  "approval.policy": "Separates draft preparation from customer-facing approval decisions.",
};
